version: "3.2"
services:
  mongodb:
    image: "mongo:4.1.13-bionic"
    container_name: "my-mongo-container"
    environment:
      - MONGO_INITDB_DATABASE=nginx_logs
      - MONGO_INITDB_ROOT_USERNAME=sweta
      - MONGO_INITDB_ROOT_PASSWORD=sweta
    volumes:
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro"
      - "mongo:/data/db"
    ports:
      - "27017:27017"
    networks:
      - logging-net

  fluentd:
    image: fluent/fluentd
    ports:
      - "24224:24224"
    networks:
      - logging-net
    depends_on:
      - "mongodb"
    volumes:
      - ./fluentd/etc:/fluentd/etc

  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - logging-net
    volumes:
      - ./usr/share/nginx/html:/usr/share/nginx/html
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: nginx-access
    depends_on:
      - "fluentd"

networks:
  logging-net:

volumes:
  mongo: