version: "3"
services:
  mongo:
    build:
      context: ./mongodb/docker
    image: 225517/mongo:3.2
    container_name: mongo-withhealthcheck
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - "mongo:/data/db"
    networks:
      - logging-net

  fluentd:
    build:
      context: ./fluentd/docker
    image: 225517/fluentd
    container_name: fluentd-withhealthcheck
    restart: unless-stopped
    ports:
      - 24224:24224
    networks:
      - logging-net
    environment:
      MONGO_URL: "mongodb://mongo:27017/nginx_logs"
      MONGO_OPLOG_URL: "mongodb://mongo:27017/local"
      MAIL_URL: "smtp://smtp.email"
    depends_on:
      - "mongo"

  nginx:
    build:
      context: ./nginx/docker
    image: 225517/nginx:mainline
    container_name: nginx-withhealthcheck
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - logging-net
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: nginx-access
    depends_on:
      - "fluentd"

networks:
  logging-net:

volumes:
  mongo: